
http:

  routers:
    nginx:
      entryPoints:
        - websecure
      rule: "Host(`test.domaine.com`)"    # CHANGE THIS
      middlewares:
        - hosts-endorsed
      service: nginx-service

  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.100"   # CHANGE THIS
